- name: Preparing to install Docker on {{ ansible_facts['distribution'] }}
  pause: 
    seconds: 5

- name: Installing dnf-plugins-core package
  dnf:
    name: dnf-plugins-core
    state: present

- name: Adding the Docker Repository
  shell: 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'

- name: Docker packages
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ docker_packages }}"

- name: Installing Docker packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

- name: Adding "{{ main_user }}" to the docker group
  user:
    name: "{{ main_user }}"
    groups: docker
    append: yes
  when: main_user != "root"
  notify: 
    - Activate Docker Group

- name: Activate Docker Group
  shell: 'newgrp docker'
  #when: main_user != "root"

# - name: Verifying the Docker installation by running a test container with the hello-world image
#   docker_container: 
#     name: hello-world
#     image: hello-world  
#   register: docker_test_output

# - name: Checking test
#   debug:
#     msg: "Docker test was successful!!!!!"
#   when: docker_test_output.stdout is search("Hello from Docker!")